#!/bin/bash

# Loads all defined colors
source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/bar.sh"
source "$CONFIG_DIR/defaults.sh"

# -- Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh
source $ITEM_DIR/music.sh
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/memory.sh
# source $ITEM_DIR/slack.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update